# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default
  
steps:

- task: PowerShell@2
  displayName: Add the username as an environment variable so the tests can find it.
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Making the BEARERTOKEN available as an environment variable."
      Write-Host "##vso[task.setvariable variable=SAUCE_USERNAME;]$(BEARERTOKEN)"
      Write-Host "Making the ORGANIZATION available as an environment variable."
      Write-Host "##vso[task.setvariable variable=ORGANIZATION;]$(ORGANIZATION)"

- task: Maven@3
  displayName: 'Run tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Path'
    mavenDirectory: $(path)
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


